CREATE TABLE IF NOT EXISTS TestTable (
    id SERIAL PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    age SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS IntegrationTable (
    id SERIAL PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    age SMALLINT NOT NULL
)
