services:
  tsql-mssql:
    container_name: tsql-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    stdin_open: true
    tty: true
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SuperStrongPassword!"
      MSSQL_PID: "Developer"
      MSSQL_COLLATION: "SQL_Latin1_General_CP1_CI_AI"
    ports:
      - 1433:1433
    volumes:
      - "./docker/sqlserver/:/tmp/"
