name: tsql
services:
  tsql-mssql:
    container_name: tsql-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    stdin_open: true
    tty: true
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SuperStrongPassword!"
      MSSQL_PID: "Developer"
      MSSQL_COLLATION: "SQL_Latin1_General_CP1_CI_AI"
    ports:
      - 1433:1433
    volumes:
      - "./docker/sqlserver/:/tmp/"
    networks:
      - devnetwork

  tsql-mysql:
    container_name: tsql-mysql
    image: mysql:latest
    platform: linux/amd64
    stdin_open: true
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "SuperStrongPassword!"
      MYSQL_DATABASE: "TestDB"
    ports:
      - 3306:3306
    command:
      [
        "mysqld",
        "--lower_case_table_names=1",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_0900_ai_ci",
      ]
    networks:
      - devnetwork

  tsql-mariadb:
    container_name: tsql-mariadb
    image: mariadb
    platform: linux/amd64
    stdin_open: true
    tty: true
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "SuperStrongPassword!"
      MARIADB_DATABASE: "TestDB"
    ports:
      - 3307:3306
    command:
      [
        "--lower_case_table_names=1",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
      ]
    networks:
      - devnetwork

networks:
  devnetwork:
