name: tsql
services:
  tsql-mssql:
    container_name: tsql-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    stdin_open: true
    tty: true
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SuperStrongPassword!"
      MSSQL_PID: "Developer"
      MSSQL_COLLATION: "SQL_Latin1_General_CP1_CI_AI"
    ports:
      - 1433:1433
    volumes:
      - "./docker/sqlserver/:/tmp/sqlserver"
    networks:
      - devnetwork

  tsql-mysql:
    container_name: tsql-mysql
    image: mysql:latest
    platform: linux/amd64
    stdin_open: true
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TestDB
      MYSQL_USER: super
      MYSQL_PASSWORD: 12345
      MYSQL_ONETIME_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD: no
    ports:
      - 3306:3306
    command:
      [
        "mysqld",
        "--lower_case_table_names=1",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_0900_ai_ci",
      ]
    volumes:
      - "./docker/mysql/:/tmp/mysql"
    networks:
      - devnetwork

  tsql-mariadb:
    container_name: tsql-mariadb
    image: mariadb:latest
    platform: linux/amd64
    stdin_open: true
    tty: true
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345
      MARIADB_DATABASE: TestDB
    ports:
      - 3307:3306
    command:
      [
        "--lower_case_table_names=1",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    volumes:
      - "./docker/mysql/:/tmp/mysql"
    networks:
      - devnetwork

  tsql-postgres:
    container_name: tsql-postgres
    image: postgres:latest
    platform: linux/amd64
    stdin_open: true
    tty: true
    restart: always
    environment:
      POSTGRES_USER: "super"
      POSTGRES_PASSWORD: "SuperStrongPassword!"
      POSTGRES_DB: "TestDB"
    ports:
      - 5432:5432
    volumes:
      - "./docker/postgres/:/tmp/postgres"
    networks:
      - devnetwork

networks:
  devnetwork:
